USE db;
DELIMITER $$
 DROP PROCEDURE IF EXISTS MODIF_SRESP$$
 CREATE PROCEDURE MODIF_SRESP()
 BEGIN
 	DECLARE fin INT; 
 	DECLARE ROW_ID_V VARCHAR(15);
 	DECLARE NAME_V VARCHAR(15);
 	DECLARE x  INT;

 SET x = 1;
 SET fin =  1;
 
 WHILE fin  <= 3600 DO
 SET ROW_ID_V=CONCAT(x,'-4ZJ7T');
 SET NAME_V=CONCAT(x, '-PRESIDENTE');
 SET  x = x + 1; 
 SET  fin = fin + 1; 
 UPDATE s_resp
 SET  NAME = NAME_V
 WHERE ROW_ID = ROW_ID_V;
 SELECT SLEEP(10);
 END WHILE;

 END$$
DELIMITER ;
	
CALL MODIF_SRESP();