USE db;
DELIMITER $$
 DROP PROCEDURE IF EXISTS INSERT_SUSER$$
 CREATE PROCEDURE INSERT_SUSER()
 BEGIN

  DECLARE fin INT; 
  DECLARE x  INT;
  DECLARE ROW_ID_V VARCHAR(15);
  DECLARE LOGIN_V VARCHAR(50);
 	
 SET x = 1;
 SET fin =  3600;
 
 WHILE fin  <= 3600 DO
 SET ROW_ID_V = CONCAT('CONT-' , x);
 SET LOGIN_V = CONCAT('LOGIN-',x);

 SET  x = x + 1; 
 INSERT INTO s_user (   
  ROW_ID ,
  LOGIN
  ) 
 VALUES 
 (
  ROW_ID_V ,
  LOGIN_V
  );
 SELECT SLEEP(1);
 END WHILE;
 END$$
DELIMITER ;
CALL INSERT_SADDRPER();