USE db;
DELIMITER $$
 DROP PROCEDURE IF EXISTS DELETE_SCONTACT_X$$
 CREATE PROCEDURE DELETE_SCONTACT_X()
 BEGIN
 	DECLARE fin INT; 
 	DECLARE ROW_ID_V VARCHAR(15);
 	DECLARE x  INT;
 SET x = 1;
 SET fin =  1;
 WHILE fin  <= 3600 DO
 SET ROW_ID_V=CONCAT('CONT-' , x);
 SET  x = x + 1; 
 SET  fin = fin + 1; 
 DELETE FROM s_contact_x WHERE ROW_ID = ROW_ID_V;
 SELECT SLEEP(20);
 END WHILE;
 END$$
DELIMITER ;
	
CALL DELETE_SCONTACT_X();
